### ISSUE TITLE
the delay settings for freeze frame refills dont work properly

### ISSUE THREAD

**Issue by ghost** [Dzhake/DzhakeHelper#1]
the delay settings for freeze frame refills dont work if "one use" is enabled.

any value higher than 0.05 will result in no freeze frames, and and any value below 0.05 will make the delay 2 frames

also setting the delay to any value less than 0.05 will result in 2 frames of delay, even if the value is set to 0

**Comment by Dzhake** [comment]
Why couldn't you just ping me on discord :\
